name: "Protobuf"
on:
  push:
    branches:
      - main
    paths:
      - "**.proto"
      - "**/buf.yaml"
      - "**/buf.lock"
      - "**/buf.md"
      - "**/README.md"
      - "**/LICENSE"

  pull_request:
    types: [ opened, synchronize, reopened ]
    branches:
      - main
      - master
    paths:
      - "**.proto"
      - "**/buf.yaml"
      - "**/buf.lock"
      - "**/buf.md"
      - "**/README.md"
      - "**/LICENSE"

  workflow_dispatch:

jobs:
  proto:
    name: "Proto"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: bufbuild/buf-action@v1