name: Protobuf lint & compile

on:
  pull_request:
    paths:
      - '**/*.proto'
    branches:
      - main

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0
        env:
          # To report GitHub Actions status checks
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  compile:
    name: Compile
    runs-on: ubuntu-latest
    needs:
      - lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Compile the proto files
        run: make proto
